=== Poussaoui/TuxGame/src/xml/dico.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns:tux="http://myGame/tux"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xsd:element name="dico" type="tux:Dico"/>
    <xsd:complexType name="Dico">
        <xsd:sequence>
            <xsd:element name="liste_mots" type="tux:Liste_mots"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Liste_mots">
        <xsd:sequence>
            <xsd:element name="mot" type="tux:Mot" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Mot">
        <xsd:simpleContent>
            <xsd:extension base="tux:MotRestreint">
                <xsd:attribute name="level" type="tux:Level" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    
    <xsd:simpleType name="MotRestreint">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-ZÀÂÊÏËÜÎÔÛÙÈÉÇa-zéèàâêïëüîôûùç]*'?\s?-?)+"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Description du type Niveau -->
    
    <xsd:simpleType name="Level">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="5"/>
        </xsd:restriction>
    </xsd:simpleType>
    
</xsd:schema>

=== Poussaoui/TuxGame/src/xml/dico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<tux:dico
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:tux='http://myGame/tux'
    xsi:schemaLocation='http://myGame/tux file:/home/m/mushingd/IM2AG/LangagePourLeWeb/TUX/src/xml/dico.xsd'>
    <tux:liste_mots>
        <tux:mot level="1">mal</tux:mot>
        <tux:mot level="1">tri</tux:mot>
        <tux:mot level="2">parler</tux:mot>
        <tux:mot level="2">manger</tux:mot>
        <tux:mot level="3">descendre</tux:mot>
        <tux:mot level="3">rabaisser</tux:mot>
        <tux:mot level="4">augmentation</tux:mot>
        <tux:mot level="4">observation</tux:mot>
        <tux:mot level="5">passe-temps</tux:mot>
        <tux:mot level="5">porte-monnaie</tux:mot>
        <tux:mot level="5">tête-à-tête</tux:mot>
    </tux:liste_mots>

</tux:dico>
